#############################################################################
# Makefile for building: release/UniversalIndentGUI.app/Contents/MacOS/UniversalIndentGUI
# Generated by qmake (2.01a) (Qt 4.4.0-tp1) on: Di Jul 15 23:31:27 2008
# Project:  UniversalIndentGUI.pro
# Template: app
# Command: /Users/thomas/Documents/Informatik/qt-static-release/bin/qmake -spec ../qt-static-release/mkspecs/macx-xcode -macx -o UniversalIndentGUI.xcodeproj/project.pbxproj UniversalIndentGUI.pro
#############################################################################

QMAKE    = /Users/thomas/Documents/Informatik/qt-static-release/bin/qmake
UniversalIndentGUI.xcodeproj/project.pbxproj: UniversalIndentGUI.pro  ../qt-static-release/mkspecs/macx-xcode/qmake.conf ../qt-static-release/mkspecs/common/unix.conf \
		../qt-static-release/mkspecs/common/mac.conf \
		../qt-static-release/mkspecs/common/mac-g++.conf \
		../qt-static-release/mkspecs/qconfig.pri \
		../qt-static-release/mkspecs/features/qt_functions.prf \
		../qt-static-release/mkspecs/features/qt_config.prf \
		../qt-static-release/mkspecs/features/exclusive_builds.prf \
		../qt-static-release/mkspecs/features/default_pre.prf \
		../qt-static-release/mkspecs/features/mac/default_pre.prf \
		../qt-static-release/mkspecs/features/release.prf \
		../qt-static-release/mkspecs/features/debug_and_release.prf \
		../qt-static-release/mkspecs/features/default_post.prf \
		../qt-static-release/mkspecs/features/mac/default_post.prf \
		../qt-static-release/mkspecs/features/mac/objective_c.prf \
		../qt-static-release/mkspecs/features/mac/sdk.prf \
		../qt-static-release/mkspecs/features/mac/ppc.prf \
		../qt-static-release/mkspecs/features/mac/x86.prf \
		../qt-static-release/mkspecs/features/warn_on.prf \
		../qt-static-release/mkspecs/features/qt.prf \
		../qt-static-release/mkspecs/features/unix/thread.prf \
		../qt-static-release/mkspecs/features/moc.prf \
		../qt-static-release/mkspecs/features/mac/rez.prf \
		../qt-static-release/mkspecs/features/resources.prf \
		../qt-static-release/mkspecs/features/uic.prf \
		../qt-static-release/mkspecs/features/yacc.prf \
		../qt-static-release/mkspecs/features/lex.prf \
		/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtScript.prl \
		/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtCore.prl \
		/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtGui.prl \
		/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtNetwork.prl
	$(QMAKE) -spec ../qt-static-release/mkspecs/macx-xcode -macx -o UniversalIndentGUI.xcodeproj/project.pbxproj UniversalIndentGUI.pro
../qt-static-release/mkspecs/common/unix.conf:
../qt-static-release/mkspecs/common/mac.conf:
../qt-static-release/mkspecs/common/mac-g++.conf:
../qt-static-release/mkspecs/qconfig.pri:
../qt-static-release/mkspecs/features/qt_functions.prf:
../qt-static-release/mkspecs/features/qt_config.prf:
../qt-static-release/mkspecs/features/exclusive_builds.prf:
../qt-static-release/mkspecs/features/default_pre.prf:
../qt-static-release/mkspecs/features/mac/default_pre.prf:
../qt-static-release/mkspecs/features/release.prf:
../qt-static-release/mkspecs/features/debug_and_release.prf:
../qt-static-release/mkspecs/features/default_post.prf:
../qt-static-release/mkspecs/features/mac/default_post.prf:
../qt-static-release/mkspecs/features/mac/objective_c.prf:
../qt-static-release/mkspecs/features/mac/sdk.prf:
../qt-static-release/mkspecs/features/mac/ppc.prf:
../qt-static-release/mkspecs/features/mac/x86.prf:
../qt-static-release/mkspecs/features/warn_on.prf:
../qt-static-release/mkspecs/features/qt.prf:
../qt-static-release/mkspecs/features/unix/thread.prf:
../qt-static-release/mkspecs/features/moc.prf:
../qt-static-release/mkspecs/features/mac/rez.prf:
../qt-static-release/mkspecs/features/resources.prf:
../qt-static-release/mkspecs/features/uic.prf:
../qt-static-release/mkspecs/features/yacc.prf:
../qt-static-release/mkspecs/features/lex.prf:
/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtScript.prl:
/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtCore.prl:
/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtGui.prl:
/Users/thomas/Documents/Informatik/qt-static-release/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../qt-static-release/mkspecs/macx-xcode -macx -o UniversalIndentGUI.xcodeproj/project.pbxproj UniversalIndentGUI.pro

