#############################################################################
# Makefile for building: debug/UniversalIndentGUI.app/Contents/MacOS/UniversalIndentGUI
# Generated by qmake (2.01a) (Qt 4.3.2) on: Do Nov 22 21:53:45 2007
# Project:  UniversalIndentGUI.pro
# Template: app
# Command: /Users/thomas/Downloads/qt_installed/bin/qmake -spec ../../../Downloads/qt_installed/mkspecs/macx-xcode -macx -o UniversalIndentGUI.xcodeproj/project.pbxproj UniversalIndentGUI.pro
#############################################################################

QMAKE    = /Users/thomas/Downloads/qt_installed/bin/qmake
UniversalIndentGUI.xcodeproj/project.pbxproj: UniversalIndentGUI.pro  ../../../Downloads/qt_installed/mkspecs/macx-xcode/qmake.conf ../../../Downloads/qt_installed/mkspecs/common/unix.conf \
		../../../Downloads/qt_installed/mkspecs/common/mac.conf \
		../../../Downloads/qt_installed/mkspecs/common/mac-g++.conf \
		../../../Downloads/qt_installed/mkspecs/qconfig.pri \
		../../../Downloads/qt_installed/mkspecs/features/qt_functions.prf \
		../../../Downloads/qt_installed/mkspecs/features/qt_config.prf \
		../../../Downloads/qt_installed/mkspecs/features/exclusive_builds.prf \
		../../../Downloads/qt_installed/mkspecs/features/default_pre.prf \
		../../../Downloads/qt_installed/mkspecs/features/mac/default_pre.prf \
		../../../Downloads/qt_installed/mkspecs/features/debug.prf \
		../../../Downloads/qt_installed/mkspecs/features/debug_and_release.prf \
		../../../Downloads/qt_installed/mkspecs/features/default_post.prf \
		../../../Downloads/qt_installed/mkspecs/features/mac/default_post.prf \
		../../../Downloads/qt_installed/mkspecs/features/mac/objective_c.prf \
		../../../Downloads/qt_installed/mkspecs/features/warn_on.prf \
		../../../Downloads/qt_installed/mkspecs/features/qt.prf \
		../../../Downloads/qt_installed/mkspecs/features/unix/thread.prf \
		../../../Downloads/qt_installed/mkspecs/features/moc.prf \
		../../../Downloads/qt_installed/mkspecs/features/mac/rez.prf \
		../../../Downloads/qt_installed/mkspecs/features/mac/sdk.prf \
		../../../Downloads/qt_installed/mkspecs/features/resources.prf \
		../../../Downloads/qt_installed/mkspecs/features/uic.prf \
		../../../Downloads/qt_installed/mkspecs/features/yacc.prf \
		../../../Downloads/qt_installed/mkspecs/features/lex.prf \
		/Users/thomas/Downloads/qt_installed/lib/libQtGui_debug.prl \
		/Users/thomas/Downloads/qt_installed/lib/libQtCore_debug.prl \
		/Users/thomas/Downloads/qt_installed/lib/libQtNetwork_debug.prl
	$(QMAKE) -spec ../../../Downloads/qt_installed/mkspecs/macx-xcode -macx -o UniversalIndentGUI.xcodeproj/project.pbxproj UniversalIndentGUI.pro
../../../Downloads/qt_installed/mkspecs/common/unix.conf:
../../../Downloads/qt_installed/mkspecs/common/mac.conf:
../../../Downloads/qt_installed/mkspecs/common/mac-g++.conf:
../../../Downloads/qt_installed/mkspecs/qconfig.pri:
../../../Downloads/qt_installed/mkspecs/features/qt_functions.prf:
../../../Downloads/qt_installed/mkspecs/features/qt_config.prf:
../../../Downloads/qt_installed/mkspecs/features/exclusive_builds.prf:
../../../Downloads/qt_installed/mkspecs/features/default_pre.prf:
../../../Downloads/qt_installed/mkspecs/features/mac/default_pre.prf:
../../../Downloads/qt_installed/mkspecs/features/debug.prf:
../../../Downloads/qt_installed/mkspecs/features/debug_and_release.prf:
../../../Downloads/qt_installed/mkspecs/features/default_post.prf:
../../../Downloads/qt_installed/mkspecs/features/mac/default_post.prf:
../../../Downloads/qt_installed/mkspecs/features/mac/objective_c.prf:
../../../Downloads/qt_installed/mkspecs/features/warn_on.prf:
../../../Downloads/qt_installed/mkspecs/features/qt.prf:
../../../Downloads/qt_installed/mkspecs/features/unix/thread.prf:
../../../Downloads/qt_installed/mkspecs/features/moc.prf:
../../../Downloads/qt_installed/mkspecs/features/mac/rez.prf:
../../../Downloads/qt_installed/mkspecs/features/mac/sdk.prf:
../../../Downloads/qt_installed/mkspecs/features/resources.prf:
../../../Downloads/qt_installed/mkspecs/features/uic.prf:
../../../Downloads/qt_installed/mkspecs/features/yacc.prf:
../../../Downloads/qt_installed/mkspecs/features/lex.prf:
/Users/thomas/Downloads/qt_installed/lib/libQtGui_debug.prl:
/Users/thomas/Downloads/qt_installed/lib/libQtCore_debug.prl:
/Users/thomas/Downloads/qt_installed/lib/libQtNetwork_debug.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../Downloads/qt_installed/mkspecs/macx-xcode -macx -o UniversalIndentGUI.xcodeproj/project.pbxproj UniversalIndentGUI.pro

