#############################################################################
# Makefile for building: release/UniversalIndentGUI.app/Contents/MacOS/UniversalIndentGUI
# Generated by qmake (2.01a) (Qt 4.4.0-tp1) on: Di Jul 15 23:31:27 2008
# Project:  UniversalIndentGUI.pro
# Template: app
# Command: /Users/thomas/Documents/Informatik/qt-static-release/bin/qmake -spec ../qt-static-release/mkspecs/macx-xcode -macx -o UniversalIndentGUI.xcodeproj/project.pbxproj UniversalIndentGUI.pro
#############################################################################

MOC       = /Users/thomas/Documents/Informatik/qt-static-release/bin/moc
UIC       = /Users/thomas/Documents/Informatik/qt-static-release/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH       = -I../qt-static-release/mkspecs/macx-xcode -I. -I../qt-static-release/include/QtCore -I../qt-static-release/include/QtCore -I../qt-static-release/include/QtNetwork -I../qt-static-release/include/QtNetwork -I../qt-static-release/include/QtGui -I../qt-static-release/include/QtGui -I../qt-static-release/include/QtScript -I../qt-static-release/include/QtScript -I../qt-static-release/include -Isrc -Irelease/moc -Irelease/uic -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./release/moc/moc_aboutdialog.cpp ./release/moc/moc_highlighter.cpp ./release/moc/moc_indenthandler.cpp\
	 ./release/moc/moc_mainwindow.cpp ./release/moc/moc_uiguierrormessage.cpp ./release/moc/moc_uiguisettings.cpp\
	 ./release/moc/moc_uiguisettingsdialog.cpp ./release/moc/moc_UiguiIndentServer.cpp ./release/moc/moc_updatecheckdialog.cpp\
	 ./release/moc/moc_AboutDialogGraphicsView.cpp ./release/qrc/qrc_Icons.cpp ./release/uic/ui_mainwindow.h ./release/uic/ui_toolBarWidget.h ./release/uic/ui_UiGuiSettingsDialog.h\
	 ./release/uic/ui_aboutdialog.h ./release/uic/ui_UpdateCheckDialog.h
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: release/moc/moc_aboutdialog.cpp release/moc/moc_highlighter.cpp release/moc/moc_indenthandler.cpp release/moc/moc_mainwindow.cpp release/moc/moc_uiguierrormessage.cpp release/moc/moc_uiguisettings.cpp release/moc/moc_uiguisettingsdialog.cpp release/moc/moc_UiguiIndentServer.cpp release/moc/moc_updatecheckdialog.cpp release/moc/moc_AboutDialogGraphicsView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) release/moc/moc_aboutdialog.cpp release/moc/moc_highlighter.cpp release/moc/moc_indenthandler.cpp release/moc/moc_mainwindow.cpp release/moc/moc_uiguierrormessage.cpp release/moc/moc_uiguisettings.cpp release/moc/moc_uiguisettingsdialog.cpp release/moc/moc_UiguiIndentServer.cpp release/moc/moc_updatecheckdialog.cpp release/moc/moc_AboutDialogGraphicsView.cpp
release/moc/moc_aboutdialog.cpp: release/uic/ui_aboutdialog.h \
		src/aboutdialog.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/aboutdialog.h -o release/moc/moc_aboutdialog.cpp

release/moc/moc_highlighter.cpp: src/highlighter.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/highlighter.h -o release/moc/moc_highlighter.cpp

release/moc/moc_indenthandler.cpp: src/uiguierrormessage.h \
		src/templateBatchScript.h \
		src/uiguiIniFileParser.h \
		src/SettingsPaths.h \
		src/indenthandler.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/indenthandler.h -o release/moc/moc_indenthandler.cpp

release/moc/moc_mainwindow.cpp: release/uic/ui_mainwindow.h \
		release/uic/ui_toolBarWidget.h \
		src/aboutdialog.h \
		release/uic/ui_aboutdialog.h \
		src/AboutDialogGraphicsView.h \
		src/uiguisettings.h \
		src/uiguisettingsdialog.h \
		release/uic/ui_UiGuiSettingsDialog.h \
		src/highlighter.h \
		src/indenthandler.h \
		src/uiguierrormessage.h \
		src/templateBatchScript.h \
		src/uiguiIniFileParser.h \
		src/SettingsPaths.h \
		src/updatecheckdialog.h \
		release/uic/ui_UpdateCheckDialog.h \
		src/mainwindow.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/mainwindow.h -o release/moc/moc_mainwindow.cpp

release/moc/moc_uiguierrormessage.cpp: src/uiguierrormessage.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/uiguierrormessage.h -o release/moc/moc_uiguierrormessage.cpp

release/moc/moc_uiguisettings.cpp: src/uiguisettings.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/uiguisettings.h -o release/moc/moc_uiguisettings.cpp

release/moc/moc_uiguisettingsdialog.cpp: release/uic/ui_UiGuiSettingsDialog.h \
		src/uiguisettings.h \
		src/uiguisettingsdialog.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/uiguisettingsdialog.h -o release/moc/moc_uiguisettingsdialog.cpp

release/moc/moc_UiguiIndentServer.cpp: src/UiguiIndentServer.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/UiguiIndentServer.h -o release/moc/moc_UiguiIndentServer.cpp

release/moc/moc_updatecheckdialog.cpp: release/uic/ui_UpdateCheckDialog.h \
		src/uiguisettings.h \
		src/updatecheckdialog.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/updatecheckdialog.h -o release/moc/moc_updatecheckdialog.cpp

release/moc/moc_AboutDialogGraphicsView.cpp: src/aboutdialog.h \
		release/uic/ui_aboutdialog.h \
		src/AboutDialogGraphicsView.h
	/Users/thomas/Documents/Informatik/qt-static-release/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/AboutDialogGraphicsView.h -o release/moc/moc_AboutDialogGraphicsView.cpp

compiler_rcc_make_all: release/qrc/qrc_Icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) release/qrc/qrc_Icons.cpp
release/qrc/qrc_Icons.cpp: resources/Icons.qrc
	/Users/thomas/Documents/Informatik/qt-static-release/bin/rcc -name Icons resources/Icons.qrc -o release/qrc/qrc_Icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: release/uic/ui_mainwindow.h release/uic/ui_toolBarWidget.h release/uic/ui_UiGuiSettingsDialog.h release/uic/ui_aboutdialog.h release/uic/ui_UpdateCheckDialog.h
compiler_uic_clean:
	-$(DEL_FILE) release/uic/ui_mainwindow.h release/uic/ui_toolBarWidget.h release/uic/ui_UiGuiSettingsDialog.h release/uic/ui_aboutdialog.h release/uic/ui_UpdateCheckDialog.h
release/uic/ui_mainwindow.h: src/mainwindow.ui
	/Users/thomas/Documents/Informatik/qt-static-release/bin/uic src/mainwindow.ui -o release/uic/ui_mainwindow.h

release/uic/ui_toolBarWidget.h: src/toolBarWidget.ui
	/Users/thomas/Documents/Informatik/qt-static-release/bin/uic src/toolBarWidget.ui -o release/uic/ui_toolBarWidget.h

release/uic/ui_UiGuiSettingsDialog.h: src/UiGuiSettingsDialog.ui
	/Users/thomas/Documents/Informatik/qt-static-release/bin/uic src/UiGuiSettingsDialog.ui -o release/uic/ui_UiGuiSettingsDialog.h

release/uic/ui_aboutdialog.h: src/aboutdialog.ui
	/Users/thomas/Documents/Informatik/qt-static-release/bin/uic src/aboutdialog.ui -o release/uic/ui_aboutdialog.h

release/uic/ui_UpdateCheckDialog.h: src/UpdateCheckDialog.ui
	/Users/thomas/Documents/Informatik/qt-static-release/bin/uic src/UpdateCheckDialog.ui -o release/uic/ui_UpdateCheckDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

