.TH UniversalIndentGUI 1 "2008-01-15" "0.8.0" "UniversalIndentGUI"

.SH NAME 
UniversalIndentGUI \- is a cross platform graphical user interface for nearly any code indenter.

.SH SYNOPSIS 
.B UniversalIndentGUI
(takes no commandline parameters)

.SH DESCRIPTION 
UniversalIndentGUI is a cross platform compatible GUI for several code formatter, beautifier and indenter like GreatCode, AStyle (Artistic Styler), GNU Indent, BCPP and so on. Main feature is a live preview to directly see how the selected formatting option affects the source code.

.SH BUGS 
Actually known bugs can be seen on http://sf.net/tracker/?func=browse&group_id=167482&atid=843127

.SH AUTHOR 
Thomas Schweitzer <thomas_-_s@users.sourceforge.net> 
